import { NextResponse } from 'next/server';
import Groq from 'groq-sdk';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { workExperience } = body;

    if (!workExperience) {
      return NextResponse.json({ error: "Work experience is required" }, { status: 400 });
    }

    const apiKey = process.env.GROQ_API_KEY;
    
    if (!apiKey) {
      return NextResponse.json({ 
        summaryInsights: "Erreur : La clé API GROQ_API_KEY est manquante dans le fichier .env.local. Veuillez redémarrer le serveur après l'avoir ajoutée." 
      });
    }

    const groq = new Groq({ apiKey });

    const completion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are an AI career coach specializing in helping individuals understand their strengths and how they apply to future roles. Analyze the work experience provided and generate summary insights. Provide your response as a JSON object with a single key 'summaryInsights'.",
        },
        {
          role: "user",
          content: `Work Experience: ${workExperience}`,
        },
      ],
      model: "llama-3.3-70b-versatile",
      response_format: { type: "json_object" },
    });

    const content = completion.choices[0]?.message?.content;
    
    if (!content) {
      throw new Error("No response generated by Groq");
    }

    const parsed = JSON.parse(content);
    return NextResponse.json({
      summaryInsights: parsed.summaryInsights || "Failed to extract insights.",
    });

  } catch (error) {
    console.error("Error generating insights with Groq:", error);
    return NextResponse.json({ 
      summaryInsights: "Désolé, une erreur est survenue lors de la génération des aperçus avec Groq." 
    }, { status: 500 });
  }
}
